version: '2'

services:

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "19511:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost:8080/info/en/about"]
      interval: 2m
      timeout: 5s
    environment:
     - SEARXNG_SECRET=${SEARXNG_SECRET}
     - SEARXNG_URL=${SEARXNG_URL}
     - BIND_ADDRESS=[::]:8080
    restart: always
networks:
  searxng:
    enable_ipv6: true
    driver: bridge
    ipam:
      config:
        - subnet: fd00:ea::/64
