version: '3.7'

services:

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "127.0.0.1:19511:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost:8080/info/en/about"]
      interval: 2m
      timeout: 5s
    environment:
    - SEARXNG_SECRET=${SEARXNG_SECRET}
    restart: always
networks:
  searxng:
    ipam:
      driver: default
