# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings:
    engines:
        keep_only:
            - google
            - google images
            - google videos
            - google news
            - bing
            - brave
            - duckduckgo
            - wikidata
            - wikipedia
            - youtube
            - apple maps
            - openstreetmap
general:
    debug: false
    instance_name: "SearXNG F2C"

server:
    base_url: "https://f3c7.dedyn.io/"
    port: 8888
    bind_address: "127.0.0.1"
    # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
    secret_key: "krvtcudiiwbuevfvvtlofneoekdbrv%$^&$&tlfdgjtygjgbnrft&^$#^#)@)_$#*)(*%shgnfgno27363!!!kevtlen" # change this!
    limiter: false # can be disabled for a private instance
    default_http_headers:
        X-Content-Type-Options: nosniff
        X-XSS-Protection: 1; mode=block
        X-Download-Options: noopen
        X-Robots-Tag: noindex, nofollow
        Referrer-Policy: no-referrer

search:
    safe_search: 0
    autocomplete: "google"
    autocomplete_min: 1
    default_lang:
      - zh-TW
      - en-US
    language:
      - zh-TW
      - en-US
    ban_time_on_fail: 60
    max_ban_time_on_fail: 120
    suspended_times:
        SearxEngineAccessDenied: 86400
        SearxEngineCaptcha: 86400
        SearxEngineTooManyRequests: 3600
        cf_SearxEngineCaptcha: 1296000
        cf_SearxEngineAccessDenied: 86400
        recaptcha_SearxEngineCaptcha: 604800

outgoing:
    request_timeout: 3
    max_request_timeout: 5

ui:
    static_use_hash: true
    query_in_title: false
    center_alignment: true
    cache_url: "https://web.archive.org/web/"
    theme_args:
      simple_style: dark

engines:
    - name: apple maps
      disabled: false
    - name: bing
      disabled: true
    - name: brave
      disabled: true
    - name: duckduckgo
      disabled: true
    - name: wikidata
      disabled: true
